apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  name: create-taxi-repo-webhook-run
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
      - name: GitHubOrg
        value: "rcdelacruz"
      - name: GitHubUser
        value: "rcdelacruz"
      - name: GitHubRepo
        value: "taxi"
      - name: GitHubSecretName
        value: webhook-secret
      - name: GitHubAccessTokenKey
        value: token
      - name: GitHubSecretStringKey
        value: secret
      - name: ExternalDomain
        value: http://github-webhook-event-listener-rcdelacruz-cicd-environment.apps.ly-demo.west.aws.redhat-demo.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
