apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  name: create-ui-repo-webhook-run
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
      - name: GitHubOrg
        value: "rcdelacruz"
      - name: GitHubUser
        value: "rcdelacruz"
      - name: GitHubRepo
        value: "vote-ui"
      - name: GitHubSecretName
        value: webhook-secret
      - name: GitHubAccessTokenKey
        value: token
      - name: GitHubSecretStringKey
        value: secret
      - name: ExternalDomain
        value: http://vote-cicd-eventlistener-pipelines-tutorial.apps.ly-demo.openshiftaws.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
